[package]
name = "cratedb"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]
description = "CrateDB driver for Rust."
repository = "https://github.com/celaus/rust-cratedb"
keywords = ["cratedb", "database", "sql", "crate"]
license = "Apache-2.0"

[dependencies]
serde = "^0.8.17"
serde_derive = "^0.8.17"
serde_json = "^0.8.3"
serde_codegen = "^0.8.17"
erased-serde = "^0.1.3"
hyper = "^0.9.12"
syntex = "^0.48.0"
